### ISSUE TITLE
Kcctl apply - Read from stdin 

### ISSUE THREAD

**Issue by Thomas-Dangleterre** [kcctl/kcctl#116]
Hi,

It would be nice to be able to read the connector configuration from stdin when calling `kcctl apply`. 

As --file option is required, it might be handled like Kubernetes by reading stdin when the option is equals to "-" : 
> Apply the JSON passed into stdin to a pod
> 
> cat pod.json | kubectl apply -f -

cf the kubectl [doc](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#apply) :

**Comment by gunnarmorling** [comment]
Interesting proposal; do you have a specific use case in mind for this? Some kind of dynamically generated config perhaps? In any case, seems like a reasonable idea to support reading config from stdin, alone for being a good CLI citizen. Wanna give it a try?

**Comment by Thomas-Dangleterre** [comment]
Yes, our connectors' configurations are injected to our pods as environnement variables.

I will gladly provide a PR :)

**Comment by gunnarmorling** [comment]
Excellent, thanks a lot and looking forward to the PR! Out of curiosity, couldn't you expose those connector configs as a config map alternatively? And as you are running on Kubernetes, have you looked into using [Strimzi](https://strimzi.io) for deploying Kafka, Connect, and connectors via custom resources? Not that I want to argue against the proposed change (I really like it), just curious about your usage :)

**Comment by Thomas-Dangleterre** [comment]
We use Helm with the image :  confluentinc/cp-kafka-connect on GKS, we did this as we copied the way we deploy our apps. We also use Vault not only as a secret manager but also as a configuration manager ( thanks to banzai cloud ) so that's why our connectors' configurations are injected as env variables.

I will take a look at Strimzi, Thanks.

**Comment by gunnarmorling** [comment]
And applied, great improvement! Thanks, @Thomas-Dangleterre!
