### ISSUE TITLE
Consider Homebrew support for macos

### ISSUE THREAD

**Issue by ruurd** [kcctl/kcctl#137]
Would you consider adding a brew recipe for this application please?

**Comment by gunnarmorling** [comment]
Hi, this already exists, please see [here](https://github.com/kcctl/kcctl#installation):

    brew install kcctl/tap/kcctl

That's for macOS/x86 only though; if you're on the M1 (AArch64), that's on our todo list, see https://github.com/kcctl/kcctl/issues/134.

**Comment by gunnarmorling** [comment]
Closing, as we already have this.
