### ISSUE TITLE
Publish binaries via sdkman

### ISSUE THREAD

**Issue by gunnarmorling** [kcctl/kcctl#14]
@aalmiray knows more about the details :)

**Comment by aalmiray** [comment]
@gunnarmorling: please request access keys at https://sdkman.io/vendors#access
Once you have those keys you can add the following repository secrets:

- JRELEASER_SDKMAN_CONSUMER_KEY
- JRELEASER_SDKMAN_CONSUMER_TOKEN

I'll take care of updating the JReleaser configuration.

Also, would you like automatic tweets when a stable release is posted?

**Comment by helpermethod** [comment]
Hi @gunnarmorling!

Do you need any help to bring this over the finish line? Would be awesome to be able to `sdk install kcctl`!

**Comment by gunnarmorling** [comment]
Thanks for the reminder; Originally, I had meant to wait with this until we have the offset display/reset features, but on second thought I think what we have is worthy of a first release and distribution through more channels. So I've just requested the deploy credentials and will create those secrets mentioned by @aalmiray above, once I have heard back. I think then it's a question of the right JReleaser configuration, any help with that will be more than welcome. Thanks!

**Comment by gunnarmorling** [comment]
@aalmiray, so what's needed in terms of configuration for actually releasing a first stable version of kcctl; can I actually run that _release_ workflow and cut a 1.0.0.Alpha1 release?

**Comment by gunnarmorling** [comment]
Ok, PR for adding a "candidate" to SDKMan has been created: https://github.com/sdkman/sdkman-db-migrations/pull/562. Waiting for the API keys now.

**Comment by aalmiray** [comment]
@gunnarmorling once you get the Sdkman credentials we have to:
1) update the root `pom.xml` to activate the sdkman packager
2) update `release.yml` with 2 additional environment variables as mentioned earlier https://github.com/kcctl/kcctl/issues/14#issuecomment-879676913

**Comment by gunnarmorling** [comment]
Hey @aalmiray, I have set up the two repository secrets as discussed before. Could you apply the required changes to the POM and JReleaser config?

**Comment by gunnarmorling** [comment]
Woohoo, kcctl is now available on SDKMan! Thank you so much, @aalmiray! Please hold off with sharing the good news more widely, I am planning to announce it properly in blog post tomorrow.
