### ISSUE TITLE
Docker build fails for EarlyAccess job

### ISSUE THREAD

**Issue by gunnarmorling** [kcctl/kcctl#146]
See https://github.com/kcctl/kcctl/actions/runs/1733660149

I suppose the GraalVM build environment doesn't have Docker installed.

**Comment by gunnarmorling** [comment]
Hey @aalmiray, that one is interesting. I am wondering how this actually worked for the regular Maven workflow (see [here](https://github.com/kcctl/kcctl/runs/4908246120?check_suite_focus=true)); it's not that we'd install Docker there either 🤔 .

**Comment by aalmiray** [comment]
Did something change recently with Docker when using the GH hosted runners?

**Comment by gunnarmorling** [comment]
Nothing I'm aware off. In particular since this just runs fine for the regular Java build, which uses the same OS base image AFAICS. Weird.

**Comment by aalmiray** [comment]
Yes, considering this was working perfectly fine just a few days ago

This issue is 2 years old https://github.community/t/why-is-docker-not-installed-on-macos/17017

**Comment by gunnarmorling** [comment]
Yeah, I suppose the issue is that Docker support may be lacking on the Windows and macOS runners. In the EA job, the Windows one failed, and then the other two got canceled. The Maven job only runs on Linux (which has Docker), and thus passed.

**Comment by gunnarmorling** [comment]
> Yes, considering this was working perfectly fine just a few days ago

Ah, sorry, I should have said that earlier: These tests requiring Docker are new, I just merged that PR an hour ago.

**Comment by aalmiray** [comment]
I see. Might need to disable them based on OS = macos and CI = true, that is you do want test to run locally but not on GitHub. I bet Junit5 has an option for that.

**Comment by gunnarmorling** [comment]
Yeah, something like that. I think I know what to do. Thanks for thinking it through with me!

**Comment by gunnarmorling** [comment]
Ok, it's working now; need to skip the Docker-based tests on macOS and Windows.

**Comment by gunnarmorling** [comment]
Not super-excited about [that solution](https://github.com/kcctl/kcctl/blob/main/.github/workflows/early-access.yml#L67-L73), but it's the easiest I found. I rather wanted an inline if/else within the `run` step, but I couldn't find a syntax that'd work on Powershell, too.

**Comment by aalmiray** [comment]
Did you try setting `shell: bash`?

**Comment by gunnarmorling** [comment]
Hum, no, didn't know that this is an option.

**Comment by aalmiray** [comment]
Yup https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell
