### ISSUE TITLE
Allow to switch between contexts

### ISSUE THREAD

**Issue by gunnarmorling** [kcctl/kcctl#19]
Having defined several named config context, it should be possible to show the current one and also switch:

```
$ kcctl config
Using configuration "local" (http://localhost:8083).

$ kcctl config use pre-prod
Using configuration "pre-prod" (http://qe:8083).

$ kcctl config use whoops
No configuration named "whoops" exists. Please run ...
```

**Comment by gunnarmorling** [comment]
// CC @helpermethod for awareness.

**Comment by helpermethod** [comment]
@gunnarmorling This requires a new field in `.kcctl` which contains the name of the current context. Maybe `current-context`?

**Comment by SiddiqueAhmad** [comment]
we should use the same commands style as here 

kcctl config get-contexts                          # display list of contexts 
kcctl config current-context                       # display the current-context
kcctl config use-context my-cluster-name           # set the default context to my-cluster-name
kcctl config set-context --current           # to set the context and also mark it as current one

what you say @gunnarmorling ?

**Comment by gunnarmorling** [comment]
+1, on both accounts, @helpermethod, @SiddiqueAhmad.

**Comment by gunnarmorling** [comment]
There's now PR #48 by @helpermethod which puts the general concept scheme in place (essentially implementing `kcctl config set-context --current`). Once that's merged, we can make progress here along the lines described by @SiddiqueAhmad above.

**Comment by gunnarmorling** [comment]
The basic set-context implementation is in place now.

**Comment by SiddiqueAhmad** [comment]
#75 is sent, it is WIP, but can be merged so far
