### ISSUE TITLE
Display task offsets

### ISSUE THREAD

**Issue by gunnarmorling** [kcctl/kcctl#2]
Upon _kcctl describe my-connector_, the task offsets should be shown. This will require to expand the notion of the configuration context, also allowing for the specification of Kafka bootstrap server URLs and the name of the offset topic.

**Comment by sfc-gh-japatel** [comment]
This is how I do it on my machine. 
```
function listConsumerGroup() {
        ~/Desktop/Kafka-Connector/snowflake-kafka-connector/test/confluent-5.5.0/bin/kafka-consumer-groups --bootstrap-server localhost:9092 --list
}

function describeConsumerGroup() {
        ~/Desktop/Kafka-Connector/snowflake-kafka-connector/test/confluent-5.5.0/bin/kafka-consumer-groups --bootstrap-server localhost:9092 --describe --group $1
}
```

I am missing something when you say configuration context.

**Comment by gunnarmorling** [comment]
> I am missing something when you say configuration context.

The idea is that you can use _kcctl_ to work with and switch between multiple "environments", i.e. Kafka Connect instances. Currently, they are just represented by the KC URL, but for the offset display/reset (see #8), we'd also need to add the Kafka bootstrap URL and name of the offset topic. I.e. like so:

```
# Define context named "local"
kcctl config set-context --name local --cluster=http://localhost:8083 --boostrap-servers=my-kafka:9092 --offset-topic=myoffsets

# Switch to another context
kcctl config use pre-prod
```

Any commands subsequently executed, like `kcctl get connectors`, will always use the currently set context.

**Comment by gunnarmorling** [comment]
@helpermethod, in case you wanted to take a stab at offset reset, the change discussed here for expaning the configuration context probably should be the first step. It'll require just a little bit of care to read back the current file format if present, which just contains the KC cluster URL. We might not have to fully support it, but logging an error message in this case would be good: "spotted earlier config file format. Please run kcctl config set-context ... again".

**Comment by sfc-gh-japatel** [comment]
I am happy to take this over if @helpermethod is fine with that. But I dont have any idea on how to achieve this? Is there a rest API which display current offsets? All I know is there is a `kafka-consumer-groups` shell script. 
CC: @gunnarmorling

**Comment by gunnarmorling** [comment]
@sfc-gh-japatel, thanks, you contribution would definitely be welcomed. Let's just wait to hear back from @helpermethod and see whether has made any progress, but I think he's more focused on the side of resetting offsets (#8).

A prerequisite for both, resetting and displaying offsets, will be expanding the `kcctl config set-context` command, so that it it also has parameters for bootstrap server and offset topic (see #24 for details, and #19 for a proposal for switching between multiple contexts):

    # local is the name of the context
    kcctl config set-context local --cluster=my-connect:8083 --bootstrap-servers=my-kafka:9092 --offset-topic=my-offsets

With that information, we then can read the information from the offset topic. @helpermethod has an earlier implementation [here](https://github.com/helpermethod/connect-offset-reset/) for resetting offsets; the code for reading and displaying them as part of the _kcctl describe_ command would look very similar.

So the first step would be to coordinate with @helpermethod who does the prequisite work described in #24; once that's in place, this issue should be not too hard to implement, following the basic logic shown in https://github.com/helpermethod/connect-offset-reset/.

**Comment by helpermethod** [comment]
Hi @sfc-gh-japatel,

feel free to implement the display offset part, I'll incorporate that into the reset 👍 .

For some inspiration on how to determine offsets, you can have a look [here](https://github.com/helpermethod/connect-offset-reset/blob/issue-36/src/main/java/com/github/helpermethod/connect/offset/reset/OffsetResetter.java).

There I already determine the task offsets before using those to perform the reset.

**Comment by gunnarmorling** [comment]
@helpermethod, so I take it you haven't started with the work on #24 and @sfc-gh-japatel could pick this one up as a first step?

**Comment by helpermethod** [comment]
Would be awesome if @sfc-gh-japatel would take on #24 :).

**Comment by gunnarmorling** [comment]
Hey @sfc-gh-japatel, @helpermethod, any news here on this issue, or the related ones? No pressure, I also can work on it myself, just wanted to check whether you got something already.

**Comment by gunnarmorling** [comment]
That's certainly ok from my side :)

>

**Comment by sfc-gh-japatel** [comment]
Sorry, I havent yet started on #24

**Comment by sfc-gh-japatel** [comment]
@helpermethod apologies, I have been busy lately. I don't think I will be able to do this at least for this month.  Feel free to grab this if you have bandwidth! Also, thanks for #24

**Comment by tonyfosterdev** [comment]
I can have a look at this if it's still open.

**Comment by tonyfosterdev** [comment]
@gunnarmorling @helpermethod @sfc-gh-japatel 

How would we want this to look? I'm not super familiar with how task offsets work, as a task could be consuming multiple topics/partitions. How do I know a particular task is associated with a particular partition?

In either case, I've got some code happening in a PR for #95 that will enable this feature. I'm playing with the admin client currently, and I believe all the data is there in the ConsumerGroup commands.

**Comment by gunnarmorling** [comment]
> How do I know a particular task is associated with a particular partition?

That's a good point; partitions are assigned to tasks upon connector start-up (it also can happen dynamically at runtime even), so the better term here would be "partition offsets". You could have a look at [kcetcd](https://github.com/gunnarmorling/kcetcd), a source connector which supports multiple tasks, for playing with the offsets. In order to obtain the information, you'd read the offsets topic (which is keyed by partition) and display the latest one per partition.

**Comment by tonyfosterdev** [comment]
Ok, that makes more sense.

Yo make sure we are on the same page, though, we would not be able to list the partition offset with the particular task it's a associated to (unless that information is available somewhere?) but can handle showing offsets for the topics and partitions.

Would it make sense to add a new section to the describe output to handle that?

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by gunnarmorling** [comment]
> we would not be able to list the partition offset with the particular task it's a associated to (unless that information is available somewhere?)

Right, I don't think we can. At least I'm not sure how we could obtain the partition-to-task mapping

> Would it make sense to add a new section to the describe output to handle that?

Yes, that sounds reasonable. We may make it opt-in (akin to the already existing `--tasks-config`).

**Comment by helpermethod** [comment]
@tonyfosterdev You may find a few pointers [here] (https://github.com/helpermethod/connor/blob/main/src/main/java/com/github/helpermethod/connor/OffsetResetter.java).

I would love to help more but my life is currently a mess and it's hard to keep up with regular work to be honest 😞. Sorry @gunnarmorling!

**Comment by gunnarmorling** [comment]
No worries at all, @helpermethod; this should be a fun project for all of us, no obligations whatsever. Wishing you all the best for dealing with whatever you need to deal with. When (and if) you'd like to return and contribute, you will be welcome to do so.

**Comment by gunnarmorling** [comment]
Hey @tonyfosterdev, are you still interested in picking this one up? I think it's the most valuable feature we have in the backlog. Happy to give it a shot myself too, if you think you won't get to it in the foreseeable future.

**Comment by tonyfosterdev** [comment]
Go ahead and give it a shot. I'm a bit swamped for the next little while through the holidays.

Thanks!

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by helpermethod** [comment]
Hi @gunnarmorling,

if it's okay for you I'll give it another try. Got a little bit of spare time on my sleeves.

**Comment by gunnarmorling** [comment]
Sure, your contribution will be more than welcome. Let me know though in
case you reconsider again, so I or Tony can pick it up; would love to see
this out eventually. Thanks!

>

**Comment by helpermethod** [comment]
Hi @gunnarmorling,

I wonder if task offsets may be stored in other formats as JSON?

**Comment by gunnarmorling** [comment]
In theory yes, as internal converters are pluggable. But this has been [deprecated since Kafka 2.0](https://cwiki.apache.org/confluence/display/KAFKA/KIP-174+-+Deprecate+and+remove+internal+converter+configs+in+WorkerConfig) and might even have been removed with 3.0 (not sure about this one though). So for all practical purposes, I think we're fine to assume the offset topic contents is JSON, and that's all I think we should support in kcctl.

**Comment by gunnarmorling** [comment]
Isn't the partition name part of this too? In fact, this issue should
probably be named "Display partition offsets", as partitions can be
shuffled between tasks and I don't think we can easily (if at all) find out
about the current assignment. You can take the kcetcd connector (
https://github.com/gunnarmorling/kcetcd/) as an example for a multi-task
connector and take a look at the format.

I haven't thought about all the details really; perhaps you can explore the
space a bit and come up with a proposal which we can discuss?

Am Di., 30. Nov. 2021 um 16:24 Uhr schrieb Oliver Weiler <
***@***.***>:

**Comment by helpermethod** [comment]
Hi @gunnarmorling,

I'm mostly done with the implementation and hope to finish it within the next few days.

**Comment by gunnarmorling** [comment]
Excellent, great news! Looking forward to the PR!

>

**Comment by gunnarmorling** [comment]
Also feel free to share an unpolished "Draft" PR early on, if you want some
quick feedback. Thanks!

>

**Comment by gunnarmorling** [comment]
@helpermethod, I did get the SDKMan access set-up btw., so we could release a first stable release any time soon. Is it still worth waiting to get this one in, or rather not?

**Comment by helpermethod** [comment]
Hi @gunnarmorling , I hope to get this in a more or less finished state today, but feel free to cut a first release before I'm finished!

**Comment by helpermethod** [comment]
Hi @gunnarmorling ,

two last (?) questions 😄. Should `offsets`or `partition-offsets` be a subcommand of `describe`?

And is showing a table with `partition` and `offset` columns enough? Or would it also help to display the `key`?

**Comment by gunnarmorling** [comment]
> Should offsetsor partition-offsets be a subcommand of describe?

How about we show this as part of `kcctl describe connector <my-connector>`? There could be a new section "Offsets", between "Tasks" and "Topics". If it's slow to retrieve that information, this could be opt-in via some parameter to that command. If the broker and offset attributes are not configured for the current context, an informational text should be printed out, stating that fact and also explaining how to provide that configuration.

> And is showing a table with partition and offset columns enough? Or would it also help to display the key?

It's a bit of both actually, as the partition name is part of the message key in the offset topic. Showing it as a table with partition and offset columns sounds good. The connector name is already shown at the top of the output of the `describe connector command`, so no need to repeat that.

**Comment by helpermethod** [comment]
Perfect! But what do you mean by partition name? Aren't partitions just numbered?

**Comment by gunnarmorling** [comment]
Ok, I think I realize now that we may have been talking about different things in this thread.

What I always had in mind here are the offsets of _source_ connectors, as persisted in the Kafka Connect specific [offset topic](https://rmoff.net/2019/08/15/reset-kafka-connect-source-connector-offsets/). These offsets describe the progress a connector has made in its _source partitions_, i.e. connector specific segments of the data source it reads from. In case of Debezium for instance, that's the latest index in the source databases TX log we've acknowledged. Taking [kcetcd](https://github.com/gunnarmorling/kcetcd/) as an example, this is how this topic looks like:

```
["etcd-test",{"name":"etcd-a"}]	{"revision":2}
["etcd-test",{"name":"etcd-c"}]	{"revision":2}
["etcd-test",{"name":"etcd-b"}]	{"revision":3}
```

The key is a combination of the connector name ("etcd-test") and a struct of one or more attributes describing the specfic source partition (in this case the etcd cluster name). Depending on the particular source, this partition could also be described by multiple attributes, e.g. a file name and an index position within this file.

This all is a notion completely separate from Kafka consumer offsets, as maintained for each consumer (and thus also Kafka Connect sink connectors), and which indeed tracks the progress of a consumer in the Kafka topic partitions (i.e. not source partitions) identified by numbers, as you say.

Eventually, it'd be nice to be able to display both kinds of offsets; but we can also start with one of the two and integrate that, just so as to move forward. WDYT?

**Comment by helpermethod** [comment]
Yes, I understood that we we're talking about connector-specific offset topics (and not consumer offsets), but wasn't aware that the task-specific offset was stored in the key. I guess the key struct is different for each connector, but it should be possible to extract and display it.

**Comment by gunnarmorling** [comment]
Ok, cool. Let's start with source offsets then.

**Comment by gunnarmorling** [comment]
Hey @helpermethod, any news here?

**Comment by helpermethod** [comment]
Hi @gunnarmorling, I'm still in it, just need a small block of uninterrupted silence to wrap things up 😁.

**Comment by gunnarmorling** [comment]
Ok, sounds good. If needed, I'll also be happy to move this over the finishing line; just create a draft PR with what you got so far in that case.

**Comment by gunnarmorling** [comment]
Hey @helpermethod, not to be pushy, but how about you create a draft PR with your work so far, so that I or someone else can wrap it up? I really would love to get this done. Thx!

**Comment by gunnarmorling** [comment]
Ok, so I think I am going to work on this, as I haven't heard back on this for multiple weeks.

**Comment by C0urante** [comment]
I've published a KIP that would add support for this to the Kafka Connect REST API; if anyone has the time to take a look, I'd be interested to hear people's thoughts: https://cwiki.apache.org/confluence/display/KAFKA/KIP-875%3A+First-class+offsets+support+in+Kafka+Connect

**Comment by gunnarmorling** [comment]
Took a quick look at this KIP, exactly what we'd need. What's the timeline for this, 3.4? The question then would be, whether we should exclusively rely on this feature, or fall back to directly reading/writing the offsets topic for earlier versions.

**Comment by C0urante** [comment]
Addressed by https://github.com/kcctl/kcctl/pull/338. Note that this feature will only work on Kafka Connect 3.5 and later.

**Comment by mfvitale** [comment]
Hi guys, I am interested in contributing to the PATCH and/or DELETE. 

Do you know if there will be a preview release with these endpoints?

**Comment by gunnarmorling** [comment]
Hey @mfvitale, welcome to the project, and thanks a lot for your interesting in contributing!

Not sure whether there are already preview releases with patch/delete support, maybe some nightly snapshot? @C0urante would know. I've logged #374 and #375 for patching and deleting offsets, respectively. Let's continue the discussion over there.

**Comment by C0urante** [comment]
AFAIK there aren't any official nightly/snapshot builds for Kafka/Kafka Connect. If we wanted to develop support for the `PATCH`/`DELETE` offset endpoints before 3.6.0 gets released, one approach would be to build Kafka Connect locally from the latest trunk (which has support for those endpoints) and test against that, possibly producing a custom Docker image that utilizes that build of Kafka Connect to facilitate both manual and automated testing.
