### ISSUE TITLE
Move repo to kcctl organization

### ISSUE THREAD

**Issue by gunnarmorling** [kcctl/kcctl#20]
Having a separate org is nicer in terms of collaboration.

@aalmiray, I've already created the org https://github.com/kcctl and am planning to move this repo over there. I assume this will require some changes to the release infra as well? Should I first do the move and you then do the required updates? Or the other way around? Thx a lot!

**Comment by aalmiray** [comment]
Yes, the early-access workflow would need to update 1 condition. Please make the move fist then I'll update the references.

**Comment by aalmiray** [comment]
Will https://github.com/gunnarmorling/kcetcd join the kcctl organization as well?

**Comment by gunnarmorling** [comment]
> Please make the move fist then I'll update the references.

Ok, will do. There's one pending PR which I'd like to get in first (will merge it in the course of the day), then I'll do the move.

> Will https://github.com/gunnarmorling/kcetcd join the kcctl organization as well?

Good question; I think I'll keep that where it is for now. I don't expect much collaboration around it at this point.

**Comment by aalmiray** [comment]
OK. Will send a quick update to this repo's JReleaser setup before the move. Then another after the move.

**Comment by gunnarmorling** [comment]
Excellent, thank you so much!

>

**Comment by gunnarmorling** [comment]
@aalmiray, the repo is now under the kcctl org (I've also sent you an invite to join that org and revoked the previous individual access).

**Comment by gunnarmorling** [comment]
@aalmiray, I think we can close this one, right?

**Comment by aalmiray** [comment]
Yup

**Comment by gunnarmorling** [comment]
Thanks again!
