### ISSUE TITLE
Add support for KIP-769

### ISSUE THREAD

**Issue by mimaison** [kcctl/kcctl#207]
[KIP-769](https://cwiki.apache.org/confluence/display/KAFKA/KIP-769%3A+Connect+APIs+to+list+all+connector+plugins+and+retrieve+their+configuration+definitions) allows listing all connector plugins and also retrieving their configuration definitions. kcctl should expose these features.

I've started working on it, hoping to have a PR soon

**Comment by gunnarmorling** [comment]
Woot, woot. Looking forward to the PR. How were you thinking to expose this, via `kcctl describe plug-in SomePlugin`?

**Comment by gunnarmorling** [comment]
Sounds great!

> `kcctl get plugins --all` to list all plugins

That would work; alternatively, how about `kcctl get plugins --type={connector|converter|transformation|predicate|all}? I.e. providing some more fine-grained control over the returned plug-in types?

**Comment by gunnarmorling** [comment]
Hey @mimaison, I think this one is actually done, or is there any remaining task here?

**Comment by mimaison** [comment]
Yes this is complete, closing.
