### ISSUE TITLE
Expand notion of configuration context

### ISSUE THREAD

**Issue by gunnarmorling** [kcctl/kcctl#24]
In order to support display (#2) and reset (#8) of connector offsets, the concept of the configuration context should be expanded. We need to have the information about the Kafka bootstrap server(s) as well as the name of the offset topic. The suggestion is to introduce a notion of _named context_ which take all the required configuration and allowing the the user to switch between them (#19).

    # local is the name of the context
    $ kcctl config set-context local --cluster=my-connect:8083 --bootstrap-servers=my-kafka:9092 --offset-topic=my-offsets
    Using context local

The information about all the configured contexts would be stored in JSON format in the _~/.kcctl_ configuration file. Commands that don't need the additional attributes, should gracefully handle the current format of _~/.kcctl_ (solely containing the KC URL). Commands which do need the additional attributes, should raise an error when encountering a file in the legacy format, indicating how to use `set-context` for updating it.

**Comment by helpermethod** [comment]
Hi @gunnarmorling,

were you thinking of something like this

```
{
  "local": {
    "connect": {
      "clusterUrl": "localhost:8083",
      "offsetTopic": "connect-offsets"
    },
    "kafka": {
      "bootstrapServer": "localhost:9092"
    }
  }
}
```

**Comment by helpermethod** [comment]
I actually wonder if YAML (or TOML) wouldn't be a better fit for a human-editable config format. But I'm also fine with JSON.

**Comment by gunnarmorling** [comment]
> were you thinking of something like this...

Yes, pretty much. Though I don't think the nesting for differentiating between AK and KC settings is even needed. I'd just go for a flat config:

```
{
  "local": {
      "clusterUrl": "localhost:8083",
      "offsetTopic": "connect-offsets",
      "bootstrapServers": "localhost:9092"
    },
  "pre-prod": {
       ...
    }
  }
}
```

> I actually wonder if YAML (or TOML) wouldn't be a better fit for a human-editable config format. But I'm also fine with JSON.

I have no strong preference either way. I suggested JSON because it seemed good enough and Jackson works in GraalVM native binaries. If there's a YAML lib which does the same, then we can use that, too. Your call :)

**Comment by helpermethod** [comment]
Ah, I see, there's a Jackson JSON extension. I guess for making it work with Jackson YAML additional work is necessary, so it's probably best to stick with JSON :).

**Comment by helpermethod** [comment]
Hi @gunnarmorling, I'm currently a little stuffed, but I hope to get back to the ticket this evening.

**Comment by helpermethod** [comment]
Okay, finally found some time! I'm on it!

**Comment by gunnarmorling** [comment]
Yeah! Note there's a command for returning the current context by now, too.

>

**Comment by helpermethod** [comment]
Okay, the configuration if now written to `kcctl` in JSON format. Probably best to also pretty-print the JSON.

![image](https://user-images.githubusercontent.com/1562019/129620757-3d53a402-1271-45d9-9bb6-b3cc69331bda.png)

**Comment by helpermethod** [comment]
Hi @gunnarmorling, while implementing the `set-cluster` part I've stumbled upon one little problem:

In order for other commands get the cluster URL, they need to know which context is currently the `active` one.

So I guess there needs to be some sort of top-level element in the JSON file, something like `current-context`. Wdyt?

**Comment by helpermethod** [comment]
Making small but steady progress... 

![image](https://user-images.githubusercontent.com/1562019/129625808-9369e530-c7eb-49ed-9719-acf22501daeb.png)

**Comment by gunnarmorling** [comment]
> So I guess there needs to be some sort of top-level element in the JSON
file, something like current-context. Wdyt?

Yes, that, or an attribute like "is-active" which is set to true on one of
the registered contexts.

>

**Comment by helpermethod** [comment]
IMHO the top-level element would be better because you could just read the element instead of having to iterate over all entries. It would also be more in line with tools like `kafkactl`.

**Comment by gunnarmorling** [comment]
Sure, it's fine either way. Your call :)

>

**Comment by helpermethod** [comment]
Another question: If the `.kcctl` file doesn't exist, *and* I create a new one with a context entry named, let's say, `local`, should that also become the new `currentContext` by default?

**Comment by gunnarmorling** [comment]
Yes, I'd say so. In general, feel free to make a decision by yourself on
things like that. I can still bring up any concerns during code review if I
feel strongly about it.

>
