### ISSUE TITLE
Make delete command more regular

### ISSUE THREAD

**Issue by gunnarmorling** [kcctl/kcctl#265]
Right now, the command to delete a connector is `kcctl delete <connector name>`. This is rather irregular, as for all the other command, the resource to act on is to be given as a sub-resource, e.g. `kcctl pause connector <connector name>`. Arguably, this is a bit more to type for those cases where there only is one kind of matching resource, but I still believe this is the better approach for the sake of regularity (e.g. `kcctl get ...` supports multiple resource types). I therefor suggest to apply the same reasoning to delete and change it into `kcctl delete connector <connector name>`.

**Comment by gunnarmorling** [comment]
@C0urante, curious about your take.

**Comment by C0urante** [comment]
Totally agree--it threw me the first time I tried to delete a connector that I didn't have to specify the resource type 👍

**Comment by gunnarmorling** [comment]
Done.
