### ISSUE TITLE
Integration tests are slow on M1 / Arm architectures

### ISSUE THREAD

**Issue by sebastienblanc** [kcctl/kcctl#289]
I noticed that my tests are running quite slowly, making my system unstable and my guess is because TestContainers is using a amd64 Kafka container : https://github.com/kcctl/kcctl/blob/main/src/test/java/org/kcctl/IntegrationTest.java#L53

 When replacing with `confluentinc/cp-kafka:7.1.5.arm64` it was more stable and fast. Maybe we can move this to configuration and make a testing profile ?

**Comment by gunnarmorling** [comment]
That's an interesting one. Shouldn't Testcontainers choose the right flavour of the Kafka image (Arm vs. x64) automatically, based on the current platform? // CC @bsideup

**Comment by gunnarmorling** [comment]
Upgraded to CP 7.3.1, and indeed things seem much faster now. Thanks for reporting, @sebastienblanc!
