### ISSUE TITLE
kcctl install from sdk requires glibc 2.32 or 2.34

### ISSUE THREAD

**Issue by hguerrero** [kcctl/kcctl#313]
When trying to install kcctl using sdkman the resulting install throws the following error:

```
kcctl: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by kcctl)
kcctl: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by kcctl)
```

This is when running on Ubuntu 20.04
```
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
```

**Comment by gunnarmorling** [comment]
Mh, yeah, the glibc version in 20.04 is too old. Could you upgrade to 22.04?

**Comment by hguerrero** [comment]
Upgrade to 22.04 works. Maybe needed to add the required min versions to the docs?

**Comment by yvespp** [comment]
On debian stable (11, bullseye) I get the same error with the package from github:
```
kcctl: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by kcctl)
kcctl: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by kcctl)
```
Sadly I can't switch the distro...

**Comment by gunnarmorling** [comment]
We may be able to to circumvent this by statically linking against (musl-)libc, as described [here](https://www.graalvm.org/22.1/reference-manual/native-image/StaticImages/).

**Comment by gunnarmorling** [comment]
I'm gonna close this one, given that 20.04 is nearly four years old at this point and folks should be on 22.04 or later by now.
