### ISSUE TITLE
Make PatchConnectorCommand more robust againt concurrent config changes

### ISSUE THREAD

**Issue by gunnarmorling** [kcctl/kcctl#357]
See https://github.com/kcctl/kcctl/actions/runs/5699964560/job/15449368506; the scope of the retry loop around one of the API calls seems not to be enough, we should do something similar for the other (read) API call. Perhaps we can extract this retry loop into a re-usable method like so:

```
Map<String, String> connectorParameters = retrying(() -> kafkaConnectApi.getConnectorConfig(conectorToPatch));
```

**Comment by gunnarmorling** [comment]
@C0urante, WDYT?

**Comment by C0urante** [comment]
Oh look, another case where automatic retries would be useful with Kafka Connect! 🙃

Yeah, thanks for catching this--the wrapper syntax looks great, will try to throw up a patch today or tomorrow.
