### ISSUE TITLE
Show help for nested subcommands

### ISSUE THREAD

**Issue by C0urante** [kcctl/kcctl#363]
There's no official way to see help messages for nested subcommands.

The usage for `kcctl` is easy to view, via `kcctl help`, `kcctl -h`, or `kcctl --help`, and provides a list of all commands along with a brief description of what each does.

The usage for any top-level commands (e.g., `kcctl apply`) is also easy to view, via `kcctl help <command>` (e.g., `kcctl help apply` or `kcctl help delete`).

If any of these commands contains nested subcommands, the subcommands are listed with a brief description of what they do. For example:

```
> kcctl help delete
Usage: kcctl delete [<args>...] [COMMAND]
Deletes connectors
      [<args>...]
Commands:
  connector  Deletes specified connector
```

However, there's no way to get usage information for those nested subcommands that doesn't involve hacks like throwing in an unrecognized flag (e.g., `-h`) that causes the command to exit with a non-zero status and print an error message. For example:

```
> kcctl delete connector -h
Unknown option: '-h'
Usage: kcctl delete connector [-e] [CONNECTOR NAME...]
Deletes specified connectors
      [CONNECTOR NAME...]   Name of the connector
  -e, --reg-exp             use CONNECTOR NAME(s) as regexp pattern(s) to apply
                              on all connectors
```

We should make it as easy as possible for users to learn about the syntax/semantics of subcommands. Some options for this include:

1. `kcctl help <command> <subcommand>` (right now this only shows the usage information for `<command>`)
2. `kcctl <command> help <subcommand>` (right now this prints an error message and then the usage information for `<command>`)
3. `kcctl <command> <subcommand> -h` and/or `kcctl <command> <subcommand> --help` (right now this prints an error message and then the usage information for `<subcommand>`)
4. `kcctl <command> <subcommand> help` (right now this invokes the subcommand with an argument of `help`)

IMO option 1 has the most intuitive syntax, but may be difficult to implement. Options 2 and 3 are straightforward to implement via the existing `CommandLine.HelpCommand` class and `mixinStandardHelpOptions` annotation option, respectively. Option 4 is also straightforward to implement with the `CommandLine.HelpCommand` class, but is a little uglier as it causes the subcommand to have its own subcommand named `help`, which pollutes usage messages a bit.

I'd like to implement option 3 unconditionally (`-h` is a deeply-ingrained reflex for many CLI users), and then either option 1 (if it can be done with reasonable effort) or option 2 (if option 1 can't be done). Interested in others' perspectives!

**Comment by gunnarmorling** [comment]
Thanks for bringing this up! I'd also lean towards option 3.

My initial reaction then was to _only_ support option 3 (as I generally prefer to not offer multiple ways for doing the same thing), but then I noticed that _kubectl_ also supports _kubectl help some-command_. And as we generally strive towards "intuition compatibility" with kubectl, I think we also should support either 1 or 2 in addition, depending on what kubectl does (couldn't find out with a quick test, does it have sub-commands like we do?), if that's doable with picocli.

In terms of consistency, I feel 2 is better than 1, as it makes _help_ a sub-command of each command, with the name of the sub-command to display the help for being an option to _help_.

**Comment by C0urante** [comment]
I forgot about the goal of syntax parity with kubectl, that's definitely worth considering.

Based on a single case study of `kubectl top` and `kubectl top node`, it looks like they've gone with options 1 and 3:

1. `kubectl help top` shows usage info for `top`, and `kubectl help top node` shows usage info for `top node`
2. `kubectl top help node` isn't recognized as a valid command
3. `kubectl top -h` and `kubectl top --help` show usage info for `top`, and `kubectl top node -h` and `kubectl top node --help` show usage info for `top node`
4. `kubectl top help` isn't recognized as a valid command, and `kubectl top node help` tries to run `top node` with an argument of `help`

Interestingly, even though it looks like all subcommands implicitly support the `-h` and `--help` flags, they are not included in the usage info for anything except the top-level command, and even that only mentions the `--help` flag.

**Comment by gunnarmorling** [comment]
>  it looks like they've gone with options 1 and 3

Sweet, then I'd say let's try and do the same, too (again, if we reasonably can within the framework provided by picocli).

> Interestingly, even though it looks like all subcommands implicitly support the -h and --help flags, they are not included in the usage info for anything except the top-level command, and even that only mentions the --help flag.

Interesting indeed. If we can, I'd deviate from kubectl's behavior in this case for the sake of consistency and display them in the usage info. Not a super-strong preference though. If you feel it should be different, I'll be happy with that too :)

**Comment by C0urante** [comment]
Great! I agree that it'd be nice to include the `-h`/`--help` flags in the usage info for any command that supports them. Will reopen #364 and see if I can clean it up to address the comments left on it.
