### ISSUE TITLE
Support patching connector offsets

### ISSUE THREAD

**Issue by gunnarmorling** [kcctl/kcctl#374]

**Comment by mfvitale** [comment]
@C0urante I have just opened a PR for the Kafka image built from trunk https://github.com/kcctl/kcctl/pull/376

**Comment by james-johnston-thumbtack** [comment]
It looks like KIP-875 has landed - it looks like kcctl would now be in a position to add commands that use the new APIs for viewing/resetting/writing offsets?  (and also stopping a connector)

**Comment by mfvitale** [comment]
Hi @james-johnston-thumbtack, the patch is the only one missing. 

The get/delete offsets and stop connector are already available.

**Comment by gunnarmorling** [comment]
Woot, woot, any takers for that one?

**Comment by C0urante** [comment]
@mfvitale yep! All that's left is patching offsets. (We also support stopping a connector; see https://github.com/kcctl/kcctl/pull/347).

**Comment by C0urante** [comment]
Self-assigned, I'll put out a PR shortly.

**Comment by C0urante** [comment]
Et voila: https://github.com/kcctl/kcctl/pull/396

**Comment by mfvitale** [comment]
@gunnarmorling Any ETA for a new release?

**Comment by gunnarmorling** [comment]
Good question. I could try and put out a CR2 right now, I don't think anything is missing really.
