### ISSUE TITLE
Remove context

### ISSUE THREAD

**Issue by Xavier-Pisco** [kcctl/kcctl#399]
I'm using kcctl and I wanted to do some tests with a specific account on my platform. I created a context with the new account and after I was done I wanted to delete that context, I didn't find a way to do this neither found an issue about this. 

For now I went to the .kcctl config file and just deleted the contexts I didn't want, but I think there should be a command, e.g. `kcctl config delete-context context-name`, for removing a context that was previously created and that's not needed anymore.

**Comment by gunnarmorling** [comment]
Good catch, we should add that. PR welcome, if you're up for it.

**Comment by Xavier-Pisco** [comment]
@gunnarmorling I created it, it's here https://github.com/kcctl/kcctl/pull/423
