### ISSUE TITLE
Have tests for kcctl

### ISSUE THREAD

**Issue by gunnarmorling** [kcctl/kcctl#44]
Currently, no tests exist for kcctl at all. We should add tests for the different commands, so to avoid regressions down the road. As part of this task, we need to

* Understand how PicoCLI applications are tested; is their any guidance in their docs?
* Set up the infrastructure for integration tests via Testcontainers; we'll need to start up ZooKeeper, Kafka, and Kafka Connect for testing kcctl; as inspiration or starting point, here's a [Docker Compose](https://github.com/gunnarmorling/kcetcd/blob/main/docker-compose.yaml) file which shows the required components; as a test connector, the built-in file connector could probably be used

**Comment by SiddiqueAhmad** [comment]
I setup the container resources class took help from debezium facing few issues, but we will do it

**Comment by karim-elngr** [comment]
The picocli documentation provide some helpful insights into [writing unit tests](https://picocli.info/#_testing_your_application)

**Comment by gunnarmorling** [comment]
Thanks, @karim-elngr, so essentially we'd just do assertions on the output stream we've set before. Makes sense. We can throw AssertJ into the mix for more expressive assertions.

@SiddiqueAhmad, ok, excellent. Seems the way forward to having some first integration tests is pretty clear then.

**Comment by karim-elngr** [comment]
I think this is worth mentioning that SDK man uses a very interesting BDD approach for testing, I wonder if there is a common approach to test cli tools

https://github.com/sdkman/sdkman-cli/blob/master/src/test/resources/features/java_installation.feature

**Comment by gunnarmorling** [comment]
That's done now thanks to a heroic effort by @iabudiab 🎉 .
