### ISSUE TITLE
Release new version of kcctl to package managers

### ISSUE THREAD

**Issue by james-johnston-thumbtack** [kcctl/kcctl#468]
The latest version in brew is v1.0.0.CR3, which doesn't have the new "delete offsets" subcommand to delete connector offsets.

It's been a few months since then... wondering if something new might be released to downstream package managers like brew?

In the meantime, I was thankfully able to unblock myself by downloading the 1.0.0-early-access release direct from GitHub.

**Comment by gunnarmorling** [comment]
Good call, I've just released v1.0.0.CR4.
