### ISSUE TITLE
Project on kcctl

### ISSUE THREAD

**Issue by SiddiqueAhmad** [kcctl/kcctl#47]
I am feeling that we should use project and kanban automated so we know which tasks should we do first and what are already in progress, is it possible, I can understand this will increase your workload, but I am seeing that it will reduce the confusions and double efforts

**Comment by gunnarmorling** [comment]
Ok, so I got to admit I'm not very keen on adding more "process" to kcctl at this point. It's a really small code base, with a few contributors mostly working on distinct parts. So far I feel that commenting on issues is good enough for having design discussions or stating the intend to pick up some task (you also can assign issues to yourself btw.).

Also, this is a side effort for all of us, so I really want to avoid the feeling for anyone that they "have to" work on something, by a given deadline. Let's keep this some fun project with everyone contributing as much (or less) they want, at a timeline that makes sense for them.

**Comment by SiddiqueAhmad** [comment]
agreed
