### ISSUE TITLE
Support using authenticated Kafka clusters

### ISSUE THREAD

**Issue by gunnarmorling** [kcctl/kcctl#95]
Hey @tonyfosterdev, IIRC, you wanted to give this a try; still up for it?

**Comment by tonyfosterdev** [comment]
Sure, I'll try to get on this when I can.

I've only used authenticated confluent clusters. Are there other types we should support?  I'll.do a little research

**Comment by tonyfosterdev** [comment]
@gunnarmorling what's the current use case for this, I want to make sure I run through that.

**Comment by tonyfosterdev** [comment]
I think #2 may make sense as a use case

**Comment by gunnarmorling** [comment]
Yes, exactly; displaying (and resetting) connector offsets would be the only time where Debezium directly interacts with Kafka Connect. In terms of auth types, the one I'd personally be interested in is SASL/PLAIN, as it's used by Red Hat's [managed Kafka offering](https://access.redhat.com/documentation/en-us/red_hat_openshift_streams_for_apache_kafka/1).

In terms of priorities, I think the actual offset display/reset would be more relevant for sure, just in case you'd be up for that one, too. I primarily had logged this one here as you were indicating interest in this (and I do think it makes sense to have it of course).

**Comment by tonyfosterdev** [comment]
Sounds good, I've started working on it, will report back!

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by gunnarmorling** [comment]
Sweet. Meant to say "where kcctl interacts with Kafka" above btw; still was early in the morning :)

**Comment by gunnarmorling** [comment]
Done via #96. Thx, @tonyfosterdev!
